stages:
    - draft
    - preprint

variables:
  title: befwm

preprint:
    stage: preprint
    script:
        - make TITLE=$title TYPE=preprint
    artifacts:
        paths:
            - befwm_preprint_version.pdf

draft:
    stage: draft
    script:
        - make TITLE=$title TYPE=draft
    artifacts:
        paths:
            - befwm_draft_version.pdf
