---
output:
    pdf_document:
        includes:
            in_header: mystyles_ED.sty
---

\begin{landscape}
\begin{table}[ht]
\centering
\resizebox{1.4\textwidth}{!}{
  \begin{tabular}{@{}lllllll@{}}
  \toprule
  Reference                                                                 & Title                                                                                                                                                                                                               & Food webs                                                                                                                    & Model reference                                                                                                                                & Growth rate function                                                                                               & Functional response                                                                                                                                                                                        & Implementation \\ \midrule
  \begin{tabular}[c]{@{}l@{}}Otto et al.,\\  2007\end{tabular}              & \begin{tabular}[c]{@{}l@{}}Allometric degree\\  distributions facilitate \\ food-web stability\end{tabular}                                                                                                         & \begin{tabular}[c]{@{}l@{}}modules from 5\\  natural food \\ webs\end{tabular}                                               & \begin{tabular}[c]{@{}l@{}}Yodzis \& \\ Ines, 1992\end{tabular}                                                                                & productivity = :species                                                                                            & Type II (:h = 1 and :c = 0)                                                                                                                                                                                & Not released   \\
  \begin{tabular}[c]{@{}l@{}}Rall et al., \\ 2007\end{tabular}              & \begin{tabular}[c]{@{}l@{}}Food-web connectance and\\  predator interference \\ dampen the paradox of \\ enrichment\end{tabular}                                                                                    & \begin{tabular}[c]{@{}l@{}}Cascade model, \\ Niche model and \\ Nested hierarchy\\  model\end{tabular}                       & \begin{tabular}[c]{@{}l@{}}Yodzis \& \\ Ines, 1992\end{tabular}                                                                                & productivity = :species                                                                                            & \begin{tabular}[c]{@{}l@{}}Type II (:h = 1, :c =0),\\  III (:h = 2, :c = 0) \\ and predator interference, (:h = 1, :c = 1) \\ or gradient (1\textless:h\textless2 and 0\textless:c\textless4)\end{tabular} & Not released   \\
  \begin{tabular}[c]{@{}l@{}}Brose,\\  2008\end{tabular}                    & \begin{tabular}[c]{@{}l@{}}Complex food webs prevent \\ competitive exclusion \\ among producer species\end{tabular}                                                                                                & Niche model                                                                                                                  & \begin{tabular}[c]{@{}l@{}}Yodzis \& \\ Ines, 1992\end{tabular}                                                                                & \begin{tabular}[c]{@{}l@{}}Producer–nutrient model \\ (Brose et al., 2005a,b)\end{tabular}                         & \begin{tabular}[c]{@{}l@{}}Hill exponent (:h) and \\ predator interference (:c) \\ randomly drawn from \\ truncated normal distributions.\end{tabular}                                                     & Not released   \\
  \begin{tabular}[c]{@{}l@{}}Williams, \\ 2008\end{tabular}                 & \begin{tabular}[c]{@{}l@{}}Effects of network and \\ dynamical model structure \\ on species persistence in \\ large model food webs\end{tabular}                                                                   & \begin{tabular}[c]{@{}l@{}}Cascade model, \\  Niche model  \\ Generalized \\ cascade model \\ and random model.\end{tabular} & \begin{tabular}[c]{@{}l@{}}Brose et al. 2006; \\ Williams et al. 2007; \\ Williams and \\ Martinez 2004; \\ Yodzis and Innes 1992\end{tabular} & \begin{tabular}[c]{@{}l@{}}:productivity = :species,\\  :system or \\ :competitive\end{tabular}                    & \begin{tabular}[c]{@{}l@{}}Type II (:h = 1, :c = 0), \\ Weak type III (:h = 1.2, :c = 0) \\ or Weak predator interference \\ (:h = 1, :c = 0.5)\end{tabular}                                               & Not released   \\
  \begin{tabular}[c]{@{}l@{}}Stouffer \&\\  Bascompte,\\  2010\end{tabular} & \begin{tabular}[c]{@{}l@{}}Understanding food-web \\ persistence from local to \\ global scales\end{tabular}                                                                                                        & Niche model                                                                                                                  & \begin{tabular}[c]{@{}l@{}}Yodzis \&\\  Ines 1992\end{tabular}                                                                                 & productivity = :species                                                                                            & Type II (:h = 1, :c = 0)                                                                                                                                                                                   & Not released   \\
  \begin{tabular}[c]{@{}l@{}}Binzer et\\  al., 2011\end{tabular}            & \begin{tabular}[c]{@{}l@{}}The susceptibility of species\\  to extinctions in  model \\ communities\end{tabular}                                                                                                    & Niche model                                                                                                                  & \begin{tabular}[c]{@{}l@{}}Yodzis \& \\ Ines, 1992\end{tabular}                                                                                & productivity = :system                                                                                             & \begin{tabular}[c]{@{}l@{}}Hill exponent (:h) and \\ predator interference (:c) \\ randomly drawn from \\ truncated normal distributions.\end{tabular}                                                     & Not released   \\
  \begin{tabular}[c]{@{}l@{}}Curtsdotter\\  et al., 2011\end{tabular}       & \begin{tabular}[c]{@{}l@{}}Robustness to secondary \\ extinctions: Comparing \\ trait-based sequential \\ deletions in static and \\ dynamic food webs\end{tabular}                                                 & Niche model                                                                                                                  & \begin{tabular}[c]{@{}l@{}}Brose, 2008; \\ Rall et al., 2008\end{tabular}                                                                      & productivity = :system                                                                                             & \begin{tabular}[c]{@{}l@{}}Hill exponent (:h) and\\  predator interference (:c) \\ randomly drawn from\\  truncated normal distributions.\end{tabular}                                                     & Not released   \\
  \begin{tabular}[c]{@{}l@{}}Stouffer \& \\ Bascompte, \\ 2011\end{tabular} & \begin{tabular}[c]{@{}l@{}}Compartmentalization \\ increases food-web \\ persistence\end{tabular}                                                                                                                   & \begin{tabular}[c]{@{}l@{}}Niche model \\ and natural \\ food webs\end{tabular}                                              & \begin{tabular}[c]{@{}l@{}}Yodzis \&\\  Ines, 1992\end{tabular}                                                                                & productivity = :species                                                                                            & Type II (:h = 1, :c = 0)                                                                                                                                                                                   & Not released   \\
  \begin{tabular}[c]{@{}l@{}}Kéfi et al., \\ 2016\end{tabular}              & \begin{tabular}[c]{@{}l@{}}How Structured Is the \\ Entangled Bank? \\ TheSurprisingly Simple \\ Organization of \\ MultiplexEcological \\ Networks Leads to \\ IncreasedPersistence and \\ Resilience\end{tabular} & \begin{tabular}[c]{@{}l@{}}Natural food \\ web and\\ randomization\end{tabular}                                              & \begin{tabular}[c]{@{}l@{}}Brose, 2008; \\ Yodzis \& Ines 1992\end{tabular}                                                                    & \begin{tabular}[c]{@{}l@{}}productivity = :competitive \\ (see Kéfi et al., 2016\\  for more details)\end{tabular} & \begin{tabular}[c]{@{}l@{}}Type III (see Kéfi et al., \\ 2016 for more details)\end{tabular}                                                                                                               & Not released   \\
  \begin{tabular}[c]{@{}l@{}}Iles \& Novak, \\ 2016\end{tabular}            & \begin{tabular}[c]{@{}l@{}}Complexity Increases \\ Predictability in \\ Allometrically Constrained\\  Food Webs\end{tabular}                                                                                        & Niche model                                                                                                                  & \begin{tabular}[c]{@{}l@{}}Williams \& \\ Martinez, 2004\end{tabular}                                                                          & productivity = :system                                                                                             & \begin{tabular}[c]{@{}l@{}}Saturating Type III–like \\ functional response :h = 3\end{tabular}                                                                                                             & Not released   \\
  Schneider et al., 2016                                                    & \begin{tabular}[c]{@{}l@{}}Animal diversity and \\ ecosystem functioning \\ in dynamic food webs\end{tabular}                                                                                                       & \begin{tabular}[c]{@{}l@{}}Simulated \\ (see Schneider et al., \\ 2016 for more details)\end{tabular}                        & Brose et al.,  2008                                                                                                                            & Producer–nutrient model                                                                                            & \begin{tabular}[c]{@{}l@{}}Hill exponent (:h) and\\  predator interference (:c) \\ randomly drawn from\\  truncated normal distributions.\end{tabular}                                                     & Released      
  \end{tabular}
}
\caption*{Table S1: List of published papers since
2007 that have used Yodzis and Ines (1992) mathematical model. The Food Webs column gives the type of data the model was applied to. The growth rate function and functional response columns show how the choice of parameters made in the papers can be reproduced using the BioEnergeticFoodwebs package.}\label{listpapers}
\end{table}
\end{landscape}
